### ISSUE TITLE
In Linux environment (php 5.3.3), html output is incomplete

### ISSUE THREAD

**Issue by funderburkjim** [drdhaval2785/github_issue_backup#27]
The text outputs seem fine, but the html output is truncated.  No obvious terminal error messages 
explain what is going on. Here's the faulty output from one html file:
![image](https://cloud.githubusercontent.com/assets/6393033/7899905/c00dfdbe-0705-11e5-94bd-ae72982786bd.png)

Here is analogous html file run under windows:
![image](https://cloud.githubusercontent.com/assets/6393033/7899909/f8d81832-0705-11e5-94ce-7d7633b37223.png)

**Comment by drdhaval2785** [comment]
@funderburkjim 
The same issue happenned to me even in windows environment, but this behaviour turned out to be due to no response from github API while fetching the text data.
cURL terminal output showed that the data was not transferred.
Comparing it with the .txt file can also show whether the data was transferred or not.
If the .txt file is OK and HTML is bad, then there is an issue.

Please re-run in linux environment and check whether the .txt file is fetched well and HTML is not shown properly, then I will have to look into presentable.php.

N.B. Right now I have cURL in silence mode `-s -S`.
If you want to see the data downloaded / not -> remove -s -S from the cURL lines.
But that would clutter the terminal output with unnecessary progress bars for each download.

**Comment by funderburkjim** [comment]
Using latest revisions,  I reran a backup at Cologne, and the html was fine.
